"""Public persistence engine API."""

from .database import create_database_engine, create_session_factory, normalize_database_url
from .models import (
    Base,
    EngineDecisionStateRecord,
    EntryOpportunityEventRecord,
    EntryOpportunityRecord,
    EntryWatchRecord,
    EntryWatchTransitionRecord,
    LongPortfolioAlertRecord,
    LongPortfolioStateRecord,
    PatreonCapsTransitionRecord,
    PatreonCapsWatchRecord,
    new_entity_id,
)
from .repositories import (
    CheckpointRepository,
    EngineDecisionStateRepository,
    EntryOpportunityRepository,
    EntryWatchRepository,
    EventPayloadConflictError,
    HealthRepository,
    InboxRepository,
    LongPortfolioAlertRepository,
    LongPortfolioStateRepository,
    OutboxRepository,
    PatreonCapsRepository,
    ProcessedEventRepository,
)
from .unit_of_work import PersistenceUnitOfWork

__all__ = [
    "Base",
    "CheckpointRepository",
    "EngineDecisionStateRecord",
    "EngineDecisionStateRepository",
    "EntryOpportunityEventRecord",
    "EntryOpportunityRecord",
    "EntryOpportunityRepository",
    "EntryWatchRecord",
    "EntryWatchRepository",
    "EntryWatchTransitionRecord",
    "EventPayloadConflictError",
    "HealthRepository",
    "InboxRepository",
    "LongPortfolioAlertRecord",
    "LongPortfolioAlertRepository",
    "LongPortfolioStateRecord",
    "LongPortfolioStateRepository",
    "OutboxRepository",
    "PatreonCapsRepository",
    "PatreonCapsTransitionRecord",
    "PatreonCapsWatchRecord",
    "PersistenceUnitOfWork",
    "ProcessedEventRepository",
    "create_database_engine",
    "create_session_factory",
    "new_entity_id",
    "normalize_database_url",
]
