"""Public v1 contracts for market-bot.

Only symbols imported here are part of the supported public contract surface.
"""

from ._base import Identifier, NonEmptyStr, SemVer, Sha256, StrictFrozenModel, new_uuid7
from .analysis_events import (
    ANALYSIS_RESULT_EVENT,
    LOCAL_ALERT_EVENT,
    MARKET_BAR_EVENT,
    MARKET_BAR_UPDATED_EVENT,
    analysis_result_subject,
    local_alert_subject,
    market_bar_subject,
)
from .domain import (
    AlertDecision,
    AlertPolicy,
    DecisionTrace,
    DependencyHealth,
    PatternCandidate,
    PatternEvidence,
    PriceLevel,
    RuleTraceStep,
    ServiceHealth,
    TradePlan,
)
from .enums import (
    AlertSeverity,
    AnalysisHorizon,
    AnalysisVerdict,
    BarTimeframe,
    DecisionOutcome,
    DependencyPolicy,
    MarketSession,
    PatternDirection,
    RuleLifecycleStatus,
    RuleStatus,
    RuleTraceStatus,
    RuleType,
    ServiceStatus,
    StrategyMode,
    TradeSide,
)
from .event_bus import EventBus, EventHandler, Subscription, SubscriptionOptions
from .market_analysis import AnalysisResult, LocalAlert, MarketBar
from .rules import (
    ContextValue,
    EvaluationContext,
    EventEnvelope,
    NamedValue,
    RuleInputDeclaration,
    RuleMetadata,
    RuleOutputDeclaration,
    RuleOutputValue,
    RulePackManifest,
    RuleResult,
)
from .strategy import (
    CompiledStrategy,
    PipelineStep,
    RuleBinding,
    ScoringPolicy,
    ScoringWeight,
    StrategyPolicies,
    StrategySpec,
    validate_primary_uniqueness,
)

__all__ = [
    "ANALYSIS_RESULT_EVENT",
    "LOCAL_ALERT_EVENT",
    "MARKET_BAR_EVENT",
    "MARKET_BAR_UPDATED_EVENT",
    "AlertDecision",
    "AlertPolicy",
    "AlertSeverity",
    "AnalysisHorizon",
    "AnalysisResult",
    "AnalysisVerdict",
    "BarTimeframe",
    "CompiledStrategy",
    "ContextValue",
    "DecisionOutcome",
    "DecisionTrace",
    "DependencyHealth",
    "DependencyPolicy",
    "EvaluationContext",
    "EventBus",
    "EventEnvelope",
    "EventHandler",
    "Identifier",
    "LocalAlert",
    "MarketBar",
    "MarketSession",
    "NamedValue",
    "NonEmptyStr",
    "PatternCandidate",
    "PatternDirection",
    "PatternEvidence",
    "PipelineStep",
    "PriceLevel",
    "RuleBinding",
    "RuleInputDeclaration",
    "RuleLifecycleStatus",
    "RuleMetadata",
    "RuleOutputDeclaration",
    "RuleOutputValue",
    "RulePackManifest",
    "RuleResult",
    "RuleStatus",
    "RuleTraceStatus",
    "RuleTraceStep",
    "RuleType",
    "ScoringPolicy",
    "ScoringWeight",
    "SemVer",
    "ServiceHealth",
    "ServiceStatus",
    "Sha256",
    "StrategyMode",
    "StrategyPolicies",
    "StrategySpec",
    "StrictFrozenModel",
    "Subscription",
    "SubscriptionOptions",
    "TradePlan",
    "TradeSide",
    "analysis_result_subject",
    "local_alert_subject",
    "market_bar_subject",
    "new_uuid7",
    "validate_primary_uniqueness",
]
