"""Public v1 contracts for market-bot.

Only symbols imported here are part of the supported public contract surface.
"""

from ._base import Identifier, NonEmptyStr, SemVer, Sha256, StrictFrozenModel, new_uuid7
from .analysis_events import (
    ANALYSIS_RESULT_EVENT,
    ELLIOTT_WAVE_ASSESSMENT_EVENT,
    ENTRY_WATCH_TRANSITION_EVENT,
    LOCAL_ALERT_EVENT,
    MARKET_BAR_EVENT,
    MARKET_BAR_UPDATED_EVENT,
    MARKET_ROTATION_EVENT,
    MARKET_ROTATION_SUBJECT,
    PATREON_CAPS_ASSESSMENT_EVENT,
    PATREON_CAPS_TRANSITION_EVENT,
    SERVICE_HEALTH_EVENT,
    analysis_result_subject,
    elliott_wave_assessment_subject,
    entry_watch_transition_subject,
    local_alert_subject,
    market_bar_subject,
    patreon_caps_assessment_subject,
    patreon_caps_transition_subject,
    service_health_subject,
)
from .domain import (
    AlertDecision,
    AlertPolicy,
    DecisionTrace,
    DependencyHealth,
    PatternCandidate,
    PatternEvidence,
    PriceLevel,
    RuleTraceStep,
    ServiceHealth,
    TradePlan,
)
from .elliott_wave import WaveAssessment
from .entry_watch import EntryWatchTransition
from .enums import (
    AlertKind,
    AlertSeverity,
    AnalysisHorizon,
    AnalysisVerdict,
    BarTimeframe,
    DecisionOutcome,
    DependencyPolicy,
    EntryWatchStatus,
    MacroRegime,
    MarketSession,
    PatreonCapsState,
    PatternDirection,
    RuleLifecycleStatus,
    RuleStatus,
    RuleTraceStatus,
    RuleType,
    ServiceStatus,
    StrategyMode,
    TradeSide,
    WavePhase,
)
from .event_bus import EventBus, EventHandler, Subscription, SubscriptionOptions
from .market_analysis import AnalysisResult, LocalAlert, MarketBar
from .market_rotation import MarketRotationReport, RotationSector
from .patreon_caps import PatreonCapsAssessment, PatreonCapsTransition
from .rules import (
    ContextValue,
    EvaluationContext,
    EventEnvelope,
    NamedValue,
    RuleInputDeclaration,
    RuleMetadata,
    RuleOutputDeclaration,
    RuleOutputValue,
    RulePackManifest,
    RuleResult,
)
from .strategy import (
    CompiledStrategy,
    PipelineStep,
    RuleBinding,
    ScoringPolicy,
    ScoringWeight,
    StrategyPolicies,
    StrategySpec,
    validate_primary_uniqueness,
)

__all__ = [
    "ANALYSIS_RESULT_EVENT",
    "ELLIOTT_WAVE_ASSESSMENT_EVENT",
    "ENTRY_WATCH_TRANSITION_EVENT",
    "LOCAL_ALERT_EVENT",
    "MARKET_BAR_EVENT",
    "MARKET_BAR_UPDATED_EVENT",
    "MARKET_ROTATION_EVENT",
    "MARKET_ROTATION_SUBJECT",
    "PATREON_CAPS_ASSESSMENT_EVENT",
    "PATREON_CAPS_TRANSITION_EVENT",
    "SERVICE_HEALTH_EVENT",
    "AlertDecision",
    "AlertKind",
    "AlertPolicy",
    "AlertSeverity",
    "AnalysisHorizon",
    "AnalysisResult",
    "AnalysisVerdict",
    "BarTimeframe",
    "CompiledStrategy",
    "ContextValue",
    "DecisionOutcome",
    "DecisionTrace",
    "DependencyHealth",
    "DependencyPolicy",
    "EntryWatchStatus",
    "EntryWatchTransition",
    "EvaluationContext",
    "EventBus",
    "EventEnvelope",
    "EventHandler",
    "Identifier",
    "LocalAlert",
    "MacroRegime",
    "MarketBar",
    "MarketRotationReport",
    "MarketSession",
    "NamedValue",
    "NonEmptyStr",
    "PatreonCapsAssessment",
    "PatreonCapsState",
    "PatreonCapsTransition",
    "PatternCandidate",
    "PatternDirection",
    "PatternEvidence",
    "PipelineStep",
    "PriceLevel",
    "RotationSector",
    "RuleBinding",
    "RuleInputDeclaration",
    "RuleLifecycleStatus",
    "RuleMetadata",
    "RuleOutputDeclaration",
    "RuleOutputValue",
    "RulePackManifest",
    "RuleResult",
    "RuleStatus",
    "RuleTraceStatus",
    "RuleTraceStep",
    "RuleType",
    "ScoringPolicy",
    "ScoringWeight",
    "SemVer",
    "ServiceHealth",
    "ServiceStatus",
    "Sha256",
    "StrategyMode",
    "StrategyPolicies",
    "StrategySpec",
    "StrictFrozenModel",
    "Subscription",
    "SubscriptionOptions",
    "TradePlan",
    "TradeSide",
    "WaveAssessment",
    "WavePhase",
    "analysis_result_subject",
    "elliott_wave_assessment_subject",
    "entry_watch_transition_subject",
    "local_alert_subject",
    "market_bar_subject",
    "new_uuid7",
    "patreon_caps_assessment_subject",
    "patreon_caps_transition_subject",
    "service_health_subject",
    "validate_primary_uniqueness",
]
